### ISSUE TITLE
Don't record the final Control-D or "exit"

### ISSUE THREAD

**Issue by awittenb** [nbedos/termtosvg#11] opened 2018-07-03 14:46 UTC
This is working great so far. My only request is to not have exiting the recording itself be recorded. It just seems like extraneous information that could potentially confuse someone (non-technical) who you are sending a recording to.

**Comment by nbedos** [comment] 2018-07-04 19:17
Not sure if this can be stripped from the recording in a consistent manner but I'll give it a try.
In the meantime you can use `termtosvg record` to get a raw recording of the session, then manually strip the last few lines of the recording and finally render the animation with `termtosvg render <filename.cast>`.

**Comment by zx2c4** [comment] 2018-07-16 01:40
As a stop-gap, you can just hack your shell... https://א.cc/GfrCqvYd/diff :frowning_face:

**Comment by nbedos** [comment] 2018-07-16 18:07
> As a stop-gap, you can just hack your shell...

I think you can achieve the same effect by sending SIGTERM to the bash process spawned by termtosvg, or as I said before by editing manually the .cast file produced by `termtosvg record`.

It's kind of a pain to implement a solution for this since termtosvg handles records (=frames of the animation) one by one. The format used for the recordings (asciicast v2) was designed with streaming in mind so having some kind of look ahead logic to handle such a special case is not ideal, although it probably can be done. I'm working on another part of the project for now but I'll look at this next.

**Comment by nbedos** [comment] 2018-12-02 21:12
I don't think there is a reliable way to implement this feature so I will be closing this issue. Those of you who need to remove the last "exit" command of a recording will have to follow the workaround given above: 
> Use `termtosvg record` to get a raw recording of the session, then manually strip the last few lines of the recording and finally render the animation with `termtosvg render <filename.cast>`.

**Closed by nbedos** 2018-12-02 21:12 UTC
Labels: enhancement
